read_lib techlib/mod_nangate45.mdt
read_lib FTL/00_Test_Addon/mod_nangate45_addon.mdt
read_netlist FTL/00_Test_Addon/threshold_test.v
report_netlist
build_circuit --frame 1
report_circuit
set_fault_type saf
add_fault --all
set_static_compression on
set_dynamic_compression on
set_X-Fill on
run_atpg
report_statistics > FTL/00_Test_Addon/rpt/threshold_test.rpt
write_pattern FTL/00_Test_Addon/pat/threshold_test.pat
write_to_STIL FTL/00_Test_Addon/pat/threshold_test.stil
exit
